### ISSUE TITLE
Translating to Russian language

### ISSUE THREAD

**Issue by ivan192** [arturkot/the-house-game#10]
Hello.
The game is very interesting!
In which files can the text be changed? I want to translate the game into Russian.

**Comment by benarascoder** [comment]
HOW TO  THAT 
 I AM STILL BEEGINNER HERE GUYS TECH ME

**Comment by ivan192** [comment]
@benarascoder, what you need?

**Comment by arturkot** [comment]
Hi,

> The game is very interesting!

Thanks!

> In which files can the text be changed? I want to translate the game into Russian.

Replying after million years. ;) Apologies. 

So, to the point. I'm afraid translating the game is going to be a tedious task. There's no central file from which the game pulls (localised) text. It's scattered across many files in the project (just reviewed them). I can see 2 paths of adding a translation:

1. Code refactor/cleanup. Extracting all the text to be translated to a separate file, then adding the logic allowing to update the language on the fly. This step could (should?) be preceded with a bunch of automated tests to ensure the game works as intended.
2. Playing with what we've got now and adding translated text in the original files.

I'd prefer the 1st option but it's a significant time investment and is not an option for me.

> I AM STILL BEEGINNER HERE GUYS TECH ME

I made this game as a complete beginner (ha!). Okay. I knew a little bit of jQuery back then. What worked for me was making stuff. Make things, fail, and learn. That's the secret sauce. :)

**Comment by ivan192** [comment]
Hi,

I have already translated the game, but some places have not been translated, as it is too long in time.

**Comment by arturkot** [comment]
Well, it would be a shame, if your work was wasted. I suggest opening up a PR with the translation. I'm not sure when we'll make it actually work _but_ at least it will be stored there waiting for its time.

**Comment by benarascoder** [comment]
> 
> 
> @benarascoder, what you need?

idk brother lets join up nd do it together whAT yiu say ?
