### ISSUE TITLE
Thank you...

### ISSUE THREAD

**Issue by randomhf398pdhg3** [arturkot/the-house-game#12]
Hi @arturkot, Amazing work indeed! Love to see all that creativity.

Thank you very much for releasing the game's code under MIT licence. Just wanted to let you know that I'm already working on the engine (room.js file) to make it a little cleaner and more efficient. (and maybe later make a game on that ). Just can't let all this beauty stay untouched ;)

Also I noticed you didn't monetized this idea even tho it's (almost) commercial-ready. Just lemme know if you have questions about marketing an indie game. I would love to help as that's the least thing I can do.

**Comment by arturkot** [comment]
Hey @randomhf398pdhg3 ,

Thanks! 

> Just wanted to let you know that I'm already working on the engine (room.js file) to make it a little cleaner and more efficient. (and maybe later make a game on that ). Just can't let all this beauty stay untouched ;)

Great to hear! 👍 I'd rewrite it from scratch TBH. :)

> Also I noticed you didn't monetized this idea even tho it's (almost) commercial-ready. Just lemme know if you have questions about marketing an indie game. I would love to help as that's the least thing I can do.

Thanks but this game has been always intended to be free and I don't intend to change that.

**Comment by randomhf398pdhg3** [comment]
I kinda finished reading the code (not all of it but I know how the game works) honestly I'm 10 times more amazed than before. Little details that players don't see while playing are everywhere (like the glow effect of window or the little smoke that comes out of boiler room on window view after you talk to furnace). The artworks are outstanding too.
> Thanks but this game has been always intended to be free and I don't intend to change that.

I see. I myself am pretty new to this but I can give you some time-saving tips on where to start marketing if you ever wanted to start another game project.
