### ISSUE TITLE
Amazing feedback

### ISSUE THREAD

**Issue by Ishaan28malik** [arturkot/the-house-game#6]
Hi Artur, I really liked the game, but not the ending.

Although it was difficult for me to solve the puzzles and complete the game.

I would definitely like to talk to you over this.
Please feel free to ping on 

ishaanmalikrm7@gmail.com

**Comment by arturkot** [comment]
> Hi Artur, I really liked the game, but not the ending.

Thanks! I wanted to add a good ending as well but never had enough time to complete it. :(

> Although it was difficult for me to solve the puzzles and complete the game.

I admit, the last puzzle is kinda out of place.

**Comment by Ishaan28malik** [comment]
So are you thinking to work on it for the ending part?

**Comment by arturkot** [comment]
It’s something I wanted to achieve years ago when I actively worked on the game. Unfortunately, I didn’t have enough time in the end. Today, assuming I’d have enough time to work on the game (and I don’t!), I’d rewrite it from scratch for better overall quality (graphics, more polished gameplay, less bugs).

**Comment by Ishaan28malik** [comment]
Sounds good !
